import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import MainHeader from "@/components/layout/MainHeader";
import MainFooter from "@/components/layout/MainFooter";

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});
const sf_pro = localFont({
  src: '../../public/assets/fonts/SF-Pro.ttf',
  variable: '--font-sf-pro'
});

export const metadata: Metadata = {
  title: "Spine - NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${sf_pro.variable}`}>
        <MainHeader />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
